### ISSUE TITLE
Implement Tensor

### ISSUE THREAD

**Issue by siliconlad** [Rust-Scientific-Computing/feotensor#1]

**Comment by CameronMatthew** [comment]
What should a tensor allow:

- creation from a flat array with a shape
- creation of identity
- creation of zeros
- creation of ones
- scalar operations
  - multiply
  - add
  - divide
  - subtract
  - power (including fractional power)
  - logical operations (>, <, == etc)
- element-wise tensor operations (between two tensors of the same shape)
  - multiply
  - add
  - divide
  - subtract
  - power (including fractional)
  - logical operations
- creation from tile of a smaller tensor
- slice a sub-tensor from an existing tensor
- iterate over one axis
- reduction operations
  - sum
  - mean
  - median
  - mode
  - max
  - min
  - stddev
- collapse operations (e.g. multiply every element in tensor together)
  - sum
  - multiply

**Comment by siliconlad** [comment]
Would the logical operators return a Boolean tensor?

**Comment by CameronMatthew** [comment]
> Would the logical operators return a Boolean tensor?

Didn't think about that lol. I guess so. But that seems like an extra type that we just don't need right now. Let's leave those out until we absolutely need them.

**Comment by siliconlad** [comment]
I suppose you could also have a tensor which has 1's and 0's for true and false respectively. So might not be too difficult to implement, but still. Probably best to wait until we need it.
